import React, { useState } from 'react';
import { FileText, Sparkles, Copy, Download, Share2, Save, Trash2, Edit3, Check, RefreshCw, Plus, Search, BookOpen } from 'lucide-react';
import { NoteItem } from '../types';
import { ExplainSimplyModal } from '../components/explain/ExplainSimplyModal';

export default function AINotesPage() {
  const [selectedSubject, setSelectedSubject] = useState('Physics');
  const [topic, setTopic] = useState('Electromagnetic Induction & Faraday Laws');
  const [loading, setLoading] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  const [activeNote, setActiveNote] = useState<NoteItem | null>({
    id: 'demo-1',
    title: 'Electromagnetic Induction & Faraday Laws',
    subject: 'Physics',
    date: '2026-07-31',
    content: 'Comprehensive notes generated by Lumora AI for board revision.',
    headings: [
      {
        title: '1. Magnetic Flux (Φ)',
        body: 'Magnetic flux through a surface of area A placed in a uniform magnetic field B is defined as Φ = B · A = BA cos(θ), where θ is the angle between B and normal to the area.'
      },
      {
        title: '2. Faraday’s Laws of Induction',
        body: 'First Law: Whenever magnetic flux linked with a closed circuit changes, an electromotive force (emf) is induced in it.\nSecond Law: The magnitude of induced emf is directly proportional to the rate of change of magnetic flux: e = -dΦ/dt.'
      },
      {
        title: '3. Lenz’s Law & Conservation of Energy',
        body: 'The direction of induced current is such that it opposes the change in magnetic flux that produced it. Signified by the negative sign in e = -N(dΦ/dt).'
      },
      {
        title: '4. Formulas & Standard Values',
        body: 'Motional emf: e = B·v·L\nSelf Inductance: L = N·Φ / I\nEnergy stored in Inductor: U = ½ L I²'
      }
    ]
  });

  const [notesList, setNotesList] = useState<NoteItem[]>([
    {
      id: '1',
      title: 'Electromagnetic Induction & Faraday Laws',
      subject: 'Physics',
      date: '2026-07-31',
      content: 'Magnetic flux, Faraday laws, Lenz law, Motional emf.',
      headings: [
        { title: '1. Magnetic Flux', body: 'Φ = B · A = BA cos(θ)' },
        { title: '2. Faraday Laws', body: 'e = -N(dΦ/dt)' }
      ]
    },
    {
      id: '2',
      title: 'Chemical Kinetics & Rate Constants',
      subject: 'Chemistry',
      date: '2026-07-29',
      content: 'Zero order, First order reactions, Arrhenius equation.',
      headings: [
        { title: '1. Rate Law', body: 'Rate = k [A]^x [B]^y' }
      ]
    }
  ]);

  const [isEditing, setIsEditing] = useState(false);
  const [copied, setCopied] = useState(false);
  
  const [explainModalOpen, setExplainModalOpen] = useState(false);
  const [explainText, setExplainText] = useState('');
  const [activeSectionIndex, setActiveSectionIndex] = useState<number | null>(null);

  const handleGenerate = () => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      const newNote: NoteItem = {
        id: Date.now().toString(),
        title: topic || `${selectedSubject} Core Revision Notes`,
        subject: selectedSubject,
        date: new Date().toISOString().split('T')[0],
        content: `Structured AI notes for ${topic}`,
        headings: [
          {
            title: '1. Core Definitions & Principles',
            body: `Fundamental concepts and definitions for ${topic}. Ensures clarity on underlying mechanics and theory.`
          },
          {
            title: '2. Key Formulas & Equations',
            body: 'Standard mathematical equations, variable constants, and SI unit guidelines required for solving numerical problems.'
          },
          {
            title: '3. High-Yield Exam Takeaways',
            body: 'Frequently asked questions, common mistakes to avoid, and step-by-step problem solving methods.'
          }
        ]
      };
      setActiveNote(newNote);
      setNotesList([newNote, ...notesList]);
    }, 1200);
  };

  const handleCopy = () => {
    if (!activeNote) return;
    const text = `# ${activeNote.title}\n\n` + activeNote.headings.map(h => `## ${h.title}\n${h.body}`).join('\n\n');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!activeNote) return;
    const text = `# ${activeNote.title}\n\n` + activeNote.headings.map(h => `## ${h.title}\n${h.body}`).join('\n\n');
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeNote.title.replace(/\s+/g, '_')}_Notes.txt`;
    a.click();
  };

  const handleDelete = (id: string) => {
    setNotesList(notesList.filter(n => n.id !== id));
    if (activeNote?.id === id) {
      setActiveNote(null);
    }
  };

  const filteredNotes = notesList.filter(n => 
    n.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
    n.subject.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="p-4 md:p-8 space-y-6 max-w-7xl mx-auto w-full">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 dark:border-slate-700/80 pb-4">
        <div>
          <div className="flex items-center gap-2 text-blue-600 dark:text-blue-400 font-bold text-xs uppercase tracking-wider">
            <FileText className="w-4 h-4" />
            <span>Lumora AI Structured Notes Library</span>
          </div>
          <h1 className="text-2xl md:text-3xl font-black text-slate-900 dark:text-white tracking-tight">
            AI Concept Notes & Formula Sheets
          </h1>
        </div>
      </div>

      {/* Generator Input Bar */}
      <div className="bg-white dark:bg-slate-800 p-5 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm grid grid-cols-1 md:grid-cols-12 gap-3 items-end">
        <div className="md:col-span-3">
          <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 mb-1">Subject</label>
          <select 
            value={selectedSubject}
            onChange={(e) => setSelectedSubject(e.target.value)}
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-xl text-xs font-semibold focus:ring-2 focus:ring-blue-500 text-slate-800 dark:text-white"
          >
            <option>Physics</option>
            <option>Chemistry</option>
            <option>Biology</option>
            <option>Mathematics</option>
            <option>Computer Science</option>
          </select>
        </div>

        <div className="md:col-span-6">
          <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 mb-1">Topic / Chapter Title</label>
          <input 
            type="text" 
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g. Electromagnetic Induction & Faraday Laws"
            className="w-full p-2.5 bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-xl text-xs font-semibold focus:ring-2 focus:ring-blue-500 text-slate-800 dark:text-white"
          />
        </div>

        <div className="md:col-span-3">
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2.5 rounded-xl text-xs shadow-lg shadow-blue-500/25 flex items-center justify-center gap-2 transition-all"
          >
            {loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            <span>{loading ? 'Creating Notes...' : 'Generate Notes'}</span>
          </button>
        </div>
      </div>

      {/* Workspace Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Saved Notes Sidebar */}
        <div className="lg:col-span-4 bg-white dark:bg-slate-800 p-5 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="font-bold text-sm text-slate-800 dark:text-slate-100 flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-blue-500" />
              <span>Notes Library ({notesList.length})</span>
            </h2>
          </div>

          <div className="relative">
            <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-3" />
            <input 
              type="text" 
              placeholder="Search notes..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-8 pr-3 py-2 bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-xl text-xs text-slate-800 dark:text-white focus:outline-none"
            />
          </div>

          <div className="space-y-2 max-h-[480px] overflow-y-auto custom-scrollbar pr-1">
            {filteredNotes.map((note) => (
              <div 
                key={note.id}
                onClick={() => setActiveNote(note)}
                className={`p-3 rounded-xl border text-left cursor-pointer transition-all ${
                  activeNote?.id === note.id
                    ? 'bg-blue-50 dark:bg-blue-900/40 border-blue-500 text-blue-900 dark:text-blue-100 shadow-xs'
                    : 'bg-slate-50 dark:bg-slate-700/30 border-slate-200 dark:border-slate-600 hover:bg-slate-100'
                }`}
              >
                <div className="flex justify-between items-center text-[10px] text-slate-400 mb-1">
                  <span className="font-bold text-blue-600 dark:text-blue-400">{note.subject}</span>
                  <span>{note.date}</span>
                </div>
                <h3 className="font-bold text-xs text-slate-800 dark:text-white line-clamp-1">{note.title}</h3>
                <p className="text-[10px] text-slate-500 dark:text-slate-400 line-clamp-2 mt-1">{note.content}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Active Note View */}
        <div className="lg:col-span-8 bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm flex flex-col justify-between min-h-[500px]">
          {activeNote ? (
            <div className="space-y-5">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-100 dark:border-slate-700 pb-4 gap-2">
                <div>
                  <span className="px-2.5 py-1 bg-blue-100 dark:bg-blue-900/50 text-blue-700 dark:text-blue-300 rounded-full text-[10px] font-bold">
                    {activeNote.subject}
                  </span>
                  <h2 className="text-xl font-extrabold text-slate-900 dark:text-white mt-1">
                    {activeNote.title}
                  </h2>
                </div>

                <div className="flex items-center gap-2">
                  <button 
                    onClick={handleCopy}
                    className="p-2 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 text-slate-700 dark:text-slate-200 rounded-xl text-xs font-bold flex items-center gap-1.5"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copied ? 'Copied' : 'Copy'}</span>
                  </button>
                  <button 
                    onClick={handleDownload}
                    className="p-2 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 text-slate-700 dark:text-slate-200 rounded-xl text-xs font-bold flex items-center gap-1.5"
                  >
                    <Download className="w-3.5 h-3.5 text-blue-500" />
                    <span>Download</span>
                  </button>
                  <button 
                    onClick={() => handleDelete(activeNote.id)}
                    className="p-2 bg-rose-50 dark:bg-rose-950/40 text-rose-600 dark:text-rose-400 rounded-xl text-xs font-bold hover:bg-rose-100"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              {/* Headings & Content */}
              <div className="space-y-4">
                {activeNote.headings.map((h, index) => (
                  <div key={index} className="p-4 bg-slate-50 dark:bg-slate-700/30 rounded-xl border border-slate-200/80 dark:border-slate-600/60 space-y-2 relative group">
                    <div className="flex justify-between items-center">
                      <h3 className="font-bold text-xs text-blue-700 dark:text-blue-400">{h.title}</h3>
                      <button
                        onClick={() => {
                          setExplainText(h.body);
                          setActiveSectionIndex(index);
                          setExplainModalOpen(true);
                        }}
                        className="px-2.5 py-1 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-lg text-[10px] font-extrabold shadow-sm hover:scale-105 transition-all flex items-center gap-1"
                      >
                        <Sparkles className="w-3 h-3 text-cyan-200" /> Explain Simply
                      </button>
                    </div>
                    <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed font-sans whitespace-pre-wrap">{h.body}</p>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="text-center py-24 text-slate-400 text-xs">
              Select or generate a note to view structured contents.
            </div>
          )}
        </div>

      </div>

      {/* EXPLAIN SIMPLY MODAL */}
      <ExplainSimplyModal
        isOpen={explainModalOpen}
        onClose={() => setExplainModalOpen(false)}
        selectedText={explainText}
        sourceContext={{
          sourceName: activeNote?.title || "Lumora AI Notes",
          chapter: activeNote?.subject || "Core Concepts"
        }}
        editableMode={true}
        onReplaceText={(newText) => {
          if (!activeNote || activeSectionIndex === null) return;
          const updatedHeadings = [...activeNote.headings];
          updatedHeadings[activeSectionIndex].body = newText;
          setActiveNote({ ...activeNote, headings: updatedHeadings });
        }}
        onInsertBelowText={(newText) => {
          if (!activeNote || activeSectionIndex === null) return;
          const updatedHeadings = [...activeNote.headings];
          updatedHeadings[activeSectionIndex].body += newText;
          setActiveNote({ ...activeNote, headings: updatedHeadings });
        }}
      />
    </div>
  );
}
